### PR TITLE
Serialization fix

### LINKED ISSUE #11: Serialization
Problem with serialization on user/admin part. 
[PROFILER SCREEN](http://joxi.ru/n2YzNBGFo5z7bA) Sometimes cause [504 error](http://joxi.ru/KAgMl0Qh46dZYm) 
ACTIONS: [set-list](https://github.com/tomfun/BranderEAVBundle/blob/master/src/Controller/RestPublicController.php#L83), [group-list](https://github.com/tomfun/BranderEAVBundle/blob/master/src/Controller/RestPublicController.php#L109
)

With serialization: [set-list](http://joxi.ru/MAjMPJWh4Lb6j2), [group-list](http://joxi.ru/ZrJqL43u9W4VeA)
Without serialization: [set-list](http://joxi.ru/RmzgP58C05ebB2), [group-list](http://joxi.ru/xAee9EPCpPEovA) 

In set-list I need additional _"attributeselect_with_options"_ group to get options in AttributeSelect. 
Also, it fixes #6 issue(partially). [Before](http://joxi.ru/52aQjyoU4D74J2) [After](http://joxi.ru/KAx5PXyTM8PMNr)
With options: [set-list](http://joxi.ru/823j740uJ40Z8m)

Final profiler: [set-list](http://joxi.ru/L21j1lMu8OMXaA), [group-list](http://joxi.ru/p27Lq1zFoxzQ5A)

### PR DESCRIPTION
**Pull request by mom666**
#11

### CODE REVIEW

File: src/Controller/RestPublicController.php [hunk 1]
```diff
@@ -110,16 +112,7 @@ public function collectionGroupAction($manage = false)
     {
         $list = $this->repoGroup->findAll();
         $cxt = SerializationContext::create();
-        if ($manage) {
-            if (!$this->securityChecker->isGranted(
```
Comment (tomfun) [inline src/Controller/RestPublicController.php]: No, left security unchanged, manage still affect http cache

File: src/Controller/RestPublicController.php [hunk 2]
```diff
@@ -83,6 +83,7 @@ class RestPublicController
     public function collectionSetAction($manage = false)
     {
         $list = $this->repoSet->findAll();
+        $cxt = SerializationContext::create();
```
Comment (tomfun) [inline src/Controller/RestPublicController.php:86]: If no manage flag do we need *Default* group?

**Review by tomfun — CHANGES_REQUESTED** [review]

File: src/Controller/RestPublicController.php (hunk 2 above)
Comment (mom666) [reply src/Controller/RestPublicController.php:86]: Done
